version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongoku:
    image: huggingface/mongoku
    restart: always
    ports:
      - 3100:3100
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://root:example@mongo:27017

  backend:
    build: backend
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - 3070:3070
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # frontend:
  #       container_name: frontend
  #       build: .
  #       volumes:
  #           - ./src:/app/src
  #       ports:
  #           - 3000:5000
